# ---------------------------------------------------------------------------
# KENYT PLATFORM — Vite/React (kenyt-ops) static app
# Note: node_modules is excluded via .dockerignore, so every shell wrapper
# (.bin/*) is regenerated by `npm install` inside this Linux container with
# the correct executable bit. The chmod below is a belt-and-suspenders
# workaround for cached layers that lost +x permissions.
# ---------------------------------------------------------------------------

# ---- Build stage ----
FROM node:20-alpine AS build

WORKDIR /app

# Copy manifests first for better layer caching; install deps.
# .npmrc carries npm fetch-retry settings (reduces "failed during network
# process"-style flaky build-builder timeouts on Railway).
COPY package*.json .npmrc ./
RUN npm install --no-audit --no-fund

# Quick workaround: restore the executable bit on all locally-installed bins,
# right after install. Guards against cached layers where .bin/* lost +x
# (commonly surfaces as `tsc: Permission denied` in PaaS build daemons).
RUN chmod +x node_modules/.bin/*

# Build the app.
# IMPORTANT: the same user runs `npm install` and `npm run build` here —
# there is NO `USER` directive between them, so both run as root consistently.
# Do not switch USER in between (a USER switch can reset PATH/bins and
# break the subsequent build).
# The start command (npm install -> npm run build) needs VITE_API_URL to be baked
# in at build time. Railway only exposes service variables to Docker builds when
# they are declared with ARG; the value is set on the frontend service
# (Reference Variable -> backend service's RAILWAY_PUBLIC_DOMAIN).
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Diagnostic: prints the resolved value in the Railway build logs so you can
# confirm the variable actually reached the Docker build.
RUN echo "VITE_API_URL is set to: ${VITE_API_URL:-<EMPTY>}"

COPY . .
RUN npm run build

# ---- Runtime stage ----
# Serve the static build with nginx. nginx listens on Railway's $PORT (rendered
# from a template at startup), which is required for the healthcheck/ingress to
# reach it.
FROM nginx:1.27-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Informational; the real port is $PORT via the entrypoint (default 8080).
EXPOSE 8080

CMD ["/docker-entrypoint.sh"]